### PR TITLE
Update repo status to OJS 2.x branch equivalent

### PR DESCRIPTION
**Pull request by asmecher**
Update the `dataverse-ojs-plugin` repo to the state of the code in the more actively maintained OJS 2.x stable branch.

Relevant commits:

https://github.com/pkp/ojs/commit/7a83171a88796cfb3392d8f14193b3aa08fe9df0
https://github.com/pkp/ojs/commit/ddf927ca63cde03f5f1b8f3e885619c08374c4cb
https://github.com/pkp/ojs/commit/978da8666f3b388b1b3027ea1eed79051dfbb06e
https://github.com/pkp/ojs/commit/ef1efaf083494e0e0871310617a51ac5eb24f240
https://github.com/pkp/ojs/commit/15f0d41b03c9ddd59c825e20982c1056f08dbb21
https://github.com/pkp/ojs/commit/ef5b895a0c3d6e7103f48d647de3c44479a3fd72
https://github.com/pkp/ojs/commit/c2c2a3169eb1744d22b1f2088c817a76b67a68b7
https://github.com/pkp/ojs/commit/e1b383e6df0bb358df853e63ff8e81e57a4a782f
https://github.com/pkp/ojs/commit/e76dea656b5774321dfea1c4ef9dc5d6f44222d7
https://github.com/pkp/ojs/commit/380d40682ff644e172fc330f2fb8edfe8cc9877a
https://github.com/pkp/ojs/commit/d33fde064be329e835bdef4842092c5e15191e95
https://github.com/pkp/ojs/commit/2c5f40fa0f12a997b05c3928435442e03603d495
https://github.com/pkp/ojs/commit/dbe779f2bd97e9a0f2842c4357fb56496b7179e4
https://github.com/pkp/ojs/commit/df8cf3dbedb8e0cddb252af89839770a49856156
https://github.com/pkp/ojs/commit/c1bc5eb377071f799973e4cd3625e3458a07e489
https://github.com/pkp/ojs/commit/609470bfb48118aa313030aa7936000ed98273ef
https://github.com/pkp/ojs/commit/e8d91ff49da5f0e1366aed6d469f456fbe84badb
https://github.com/pkp/ojs/commit/f3092ad699347a9c811e0f67ede9386c26242e94
https://github.com/pkp/ojs/commit/82c633291bc1708d58e9a6c0a0842bbeb2937b04
https://github.com/pkp/ojs/commit/b6be462a8f40cb0748d331bada1355bb595c0120
https://github.com/pkp/ojs/commit/c6662adc1831e594b06c739009dfe868d4143aee
https://github.com/pkp/ojs/commit/ce188258dd53392e47c9944a3890c04d60ed4720
https://github.com/pkp/ojs/commit/e1a826c758af76a16e106c96cfe7b734bfdefce0
https://github.com/pkp/ojs/commit/f4d65d84b3604db90c929a6e05a6c2827bea30c1
https://github.com/pkp/ojs/commit/28c4b1bc41d1ca97e81683c4704bad4cd9b9511b
https://github.com/pkp/ojs/commit/0d812103ed31b670975051147a6908fce90adafc
https://github.com/pkp/ojs/commit/62452572488d9aef02597d1adc62cbee26cab3e0
https://github.com/pkp/ojs/commit/9b47677751f83f444ae8f821a0b45c9f13ae919a
https://github.com/pkp/ojs/commit/21c721b2c77871cccabf7b64661dd65cdad084e3
https://github.com/pkp/ojs/commit/fa3ad982a446ed32b3cd281baa3b359054d8988b
https://github.com/pkp/ojs/commit/f4cf6ed7bb782c0c0a9f0afaa4e6fc1ecfccdd77
https://github.com/pkp/ojs/commit/929ab9725e57c8ea240529113c86aaa69ba8453b
https://github.com/pkp/ojs/commit/2dd1787f21a989c14ca75bca1ad088d8cefa65f9
https://github.com/pkp/ojs/commit/7c33cdba80324678c148bb142d5367e48ce68ef2
https://github.com/pkp/ojs/commit/228898964f017c45b6367bfc5d4b1e726dc9d64e
https://github.com/pkp/ojs/commit/0154003948a7207e499817a7e42639ca43dd1a2b
https://github.com/pkp/ojs/commit/ff24c38e70c83a18368ae0fa3373f0d8b8630873
https://github.com/pkp/ojs/commit/567fa5560bc373759339a11f9cbd9db0f83baa20
https://github.com/pkp/ojs/commit/5ade29b7af6563645315c393768d275707eaddef
https://github.com/pkp/ojs/commit/13b183f4e2797de0a0f850e23840313b9dd5c59a
https://github.com/pkp/ojs/commit/ac89fc6bf03d02e6c9025be89841a423ca390592
https://github.com/pkp/ojs/commit/784ffbe8e63dd2ebfd19171f6b9aef0e776f491d
https://github.com/pkp/ojs/commit/bd48a4eb8926b8ef3e956ca1d1a834e88545b9d2
https://github.com/pkp/ojs/commit/b2e87cf3860090ad504f31181a767035534a5c6a
https://github.com/pkp/ojs/commit/649bf6aef1c4a8cad0acf3b62052d12178f8bfe8
https://github.com/pkp/ojs/commit/9fcbb4403eca312bc99a6842d6213c8295ae4694
https://github.com/pkp/ojs/commit/9588b832ec946f1fea30f3b4c1b90f3310e3381c
https://github.com/pkp/ojs/commit/6c8707be5b273f13691cf42fa01e878746c38638
https://github.com/pkp/ojs/commit/fc5881fd94e894e93b79c32685c49e40a5d4c426
https://github.com/pkp/ojs/commit/f94c32c9a6895965bd22b64f9f85f748eea9b99a
https://github.com/pkp/ojs/commit/ac4e98a8b6b73f1aa144c4058b73da39d649e2a6
https://github.com/pkp/ojs/commit/b8ed4e9430a16d593ba887695c9148c3b7657dbd
https://github.com/pkp/ojs/commit/bc60e78a502ed3bc8a4534c52ad3bb1d0c5b8b1d
https://github.com/pkp/ojs/commit/daa9968725e04f2b79fd35f410e3a61ce1e642bf
https://github.com/pkp/ojs/commit/4a75271a4f67509d1534e6cd9df45ac23af36010
https://github.com/pkp/ojs/commit/5e4e07d3b6f5d4a7e44fd82b85957a5d3b526525
https://github.com/pkp/ojs/commit/083b248653ff7c891105b45ab6b67d30bad51084
https://github.com/pkp/ojs/commit/ac6023f7b43e35e331c0b6c27927762f7ca49493
https://github.com/pkp/ojs/commit/2a2ce69405053a4492597839349309df59f5abfe
https://github.com/pkp/ojs/commit/334544de5c78e0ad7d6471bb3b19d51e73616246
https://github.com/pkp/ojs/commit/f4c066a6b2d1fb530cd0e5c31b36818fec342a93
https://github.com/pkp/ojs/commit/fed414ce6e46d4315784dae0139ad7487a37b314
https://github.com/pkp/ojs/commit/2b6954ee2a028a18a8235fc379463e4fecb9b9b5
https://github.com/pkp/ojs/commit/756e22c744f4a795e1d5fb2600a1e262f4b5b7d7
https://github.com/pkp/ojs/commit/f9ac453ae458b1474cf7784c36c97113ced83093
https://github.com/pkp/ojs/commit/e3f46b143019abeabd9ad92fdc273938af573ff5
https://github.com/pkp/ojs/commit/f2ad896b7e32f22950f6c97cca8c0e7a9c87b8ce
https://github.com/pkp/ojs/commit/1ab1bf1214b158c097b3d7e955caa8a510f254de
https://github.com/pkp/ojs/commit/496f1f0282e8711a8f1d939d8d85ac652cb15ce1
https://github.com/pkp/ojs/commit/0146211a7c0c6ea37ea3518a196e7cafeb7c1def
https://github.com/pkp/ojs/commit/7f4b6b7f891a55a245b249b805cfde5a54123c27
https://github.com/pkp/ojs/commit/580c31afe290edec696a63a69e09f657b4451c52
https://github.com/pkp/ojs/commit/af3bb850796ee2a38d4a75c3099ce3c0fb1f8909
https://github.com/pkp/ojs/commit/71fac38b9b7c5540c8ee6d14163ff173f823c8f3
https://github.com/pkp/ojs/commit/e400c87dbd7f6110bc40d233dc3342baa8b0feef
https://github.com/pkp/ojs/commit/8e49845e5bc2e099c2951b73dc326cda90e44f3f
https://github.com/pkp/ojs/commit/69c0466c70fb488df0e631430d5663d960bef40a
https://github.com/pkp/ojs/commit/3000ced7f3c03969f91d690ba78795ff3ae177a0
https://github.com/pkp/ojs/commit/a40d3373284391505271c7f47b905c05cf758bed
https://github.com/pkp/ojs/commit/43bd6620fdd58452d5256e43b7cdcded43d689ee
https://github.com/pkp/ojs/commit/a0ef45de97fb5f5b8018a3f0e04b3eae9e73daf8
https://github.com/pkp/ojs/commit/f000ff54a680fccec4971d6cfa105be53b0c3e58
https://github.com/pkp/ojs/commit/5763e81b1276c89def58b326a2f48d39c33496fc
https://github.com/pkp/ojs/commit/a636f8689c7f7694847a5317f29989e29cc20e3d
https://github.com/pkp/ojs/commit/8e7c895d871e77bb589406f88dfb5bfd56ce8270
https://github.com/pkp/ojs/commit/c65928b5f2c642991ad3eb3df6feb65d132bdde8
https://github.com/pkp/ojs/commit/d916dcb6316d03d8c08e23ded5690579109247bf
https://github.com/pkp/ojs/commit/8ecccf1b817e04f0ad883b8fbe2d25dcce54ac00
https://github.com/pkp/ojs/commit/8fa3ac7d90c18da0a3fa25260fa6e0c7570c405f
https://github.com/pkp/ojs/commit/7b235402154c136f62dd12453f707dc98b0a831d
https://github.com/pkp/ojs/commit/a0923fc3b074747df4f5824dac8425cd2e4681c8
https://github.com/pkp/ojs/commit/c69516e5c000f2b43884c1e7338640d01f23307f
https://github.com/pkp/ojs/commit/6de98f81b558ade34dfe7aa5a60d7a7ce2240e26
https://github.com/pkp/ojs/commit/049c81ffd3ed0ca7e532e3228d4fff969b5664aa
https://github.com/pkp/ojs/commit/d6d2a75543f0dad7d82cccd3d7a2cf69e024eccb
https://github.com/pkp/ojs/commit/aee3056a40fc29736796a5e21288605d2dbbaf37
https://github.com/pkp/ojs/commit/5130b5966cdeb796da961aaa7ea2c6bfcf946084
https://github.com/pkp/ojs/commit/5af399f16abc14fe730cff2707f95682f854fa5b
https://github.com/pkp/ojs/commit/ac93337f3f80745dc3ae5ff9a65c4be4f18f479c
https://github.com/pkp/ojs/commit/a710ef277e900bcf82a169f685ba08dbf9981fd0
https://github.com/pkp/ojs/commit/a839da46937acf7bde62fc4ea35baac0e173e743

### CODE REVIEW

**Comment by pdurbin** [comment]
@asmecher thanks for this pull request! I moved this to code review in our board at https://github.com/orgs/IQSS/projects/2

To give code reviewers and the community some context, I just posted this: https://groups.google.com/d/msg/dataverse-community/d_8aZnav4KE/U_qUSXUzAAAJ

**Comment by djbrooke** [comment]
Thanks @asmecher for the PR and @pdurbin for the note. I'm OK if the core team at IQSS doesn't review this one since it's community supported. 

@qqmyers - heads up in case you want to review or join in coordination efforts from the GDCC perspective.

**Comment by uuskhusni** [comment]
on progress, thank you

**Comment by pdurbin** [comment]
@uuskhusni thanks for reviewing and merging!

@asmecher thanks again for the pull request!

Heads up to @oodu about this new repo!

Go, go, go! 🎉

**Pull request merged**
